/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zeusis_mydynamic_JavaNative */

#ifndef _Included_com_zeusis_mydynamic_JavaNative
#define _Included_com_zeusis_mydynamic_JavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zeusis_mydynamic_JavaNative
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zeusis_mydynamic_JavaNative_nativeAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zeusis_mydynamic_JavaNative
 * Method:    nativeHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zeusis_mydynamic_JavaNative_nativeHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
